name: build and test with Qt5

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: setup environment
      run: |
        sudo apt-get install --no-install-recommends \
          cmake \
          g++ \
          git \
          libasio-dev \
          libboost-test-dev \
          libtclap-dev \
          ninja-build \
          nlohmann-json3-dev \
          qtbase5-dev \
          ruby \
          ruby-dev

    - name: install ruby tools
      run: |
        sudo gem install bundler
        sudo bundle install

    - name: install gtest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ../
        cmake --build . --parallel
        sudo cmake --install .

    - name: build
      run: |
        cmake -E make_directory build
        cmake -E chdir build cmake \
          -G Ninja \
          -DCUKE_STRICT=on \
          -DCUKE_ENABLE_BOOST_TEST=on \
          -DCUKE_ENABLE_GTEST=on \
          -DCUKE_ENABLE_QT_5=on \
          -DCUKE_ENABLE_EXAMPLES=on \
          -DCUKE_TESTS_UNIT=on \
          ..
        cmake --build build --parallel --verbose

    - name: unit tests
      run: |
        cmake --build build --target test

    - name: QtCalc examples
      run: |
        for TEST in \
          build/examples/CalcQt/GTestCalculatorQtSteps \
          build/examples/CalcQt/QtTestCalculatorQtSteps \
          build/examples/CalcQt/BoostCalculatorQtSteps \
        ; do
          "${TEST}" 2> /dev/null &
          sleep 1
          (cd examples/CalcQt; cucumber)
          wait %
        done
