name: run all

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: setup environment
      run: |
        sudo apt-get install --no-install-recommends \
        cmake \
        g++ \
        gcovr \
        git \
        libasio-dev \
        libboost-test-dev \
        libtclap-dev \
        make \
        ninja-build \
        nlohmann-json3-dev \
        qtbase5-dev \
        ruby \
        ruby-dev \
        xvfb

    - name: install ruby tools
      run: |
        sudo gem install bundler
        sudo bundle install

    - name: install gtest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ../
        cmake --build . --parallel
        sudo cmake --install .

    - name: build and run
      run: |
        export DISPLAY=:99
        ./run-all.sh

    - name: code coverage summary report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/cobertura.xml
        indicators: false
        hide_complexity: true
        format: markdown
        output: file

    - name: publish code coverage summary
      run: |
        echo '# Code Coverage Report' >> $GITHUB_STEP_SUMMARY
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

