name: run all

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: update package index
      run: sudo apt-get -y update

    - name: setup environment
      run: |
        sudo apt-get install --no-install-recommends \
          cmake \
          g++ \
          gcovr \
          git \
          libasio-dev \
          libboost-test-dev \
          libgl1-mesa-dev \
          libtclap-dev \
          ninja-build \
          nlohmann-json3-dev \
          qt6-base-dev \
          ruby \
          ruby-dev

    - name: install ruby tools
      run: |
        sudo gem install bundler
        sudo bundle install

    - name: install gtest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ../
        cmake --build . --parallel
        sudo cmake --install .

    - name: build and run
      run: |
        ./run-linux.sh

    - name: code coverage summary report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/cobertura.xml
        indicators: false
        hide_complexity: true
        format: markdown
        output: file

    - name: publish code coverage summary
      run: |
        echo '# Code Coverage Report' >> $GITHUB_STEP_SUMMARY
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
